image: amazon/aws-cli

.set_environment: &setenv |
  export DOCKER_REPO=${DOCKER_REGISTRY}/${BITBUCKET_REPO_SLUG}
  export IMAGE_TAG=${DOCKER_REPO}:${BITBUCKET_COMMIT::7}
  export DOCKERFILE_PATH=Dockerfile
  env
  aws configure set aws_access_key_id "${AWS_KEY}"
  aws configure set aws_secret_access_key "${AWS_SECRET}"
  aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}

.build_and_push_images: &build_and_push_images |
  docker build . --file ${DOCKERFILE_PATH} --tag ${IMAGE_TAG}
  docker push ${IMAGE_TAG}

.pull_images: &pull_images |
  docker pull ${IMAGE_TAG}

.retag_and_push_images: &retag_and_push_images |
  docker tag ${IMAGE_TAG} ${NEW_IMAGE_TAG}
  docker push ${NEW_IMAGE_TAG}

definitions:
  services:
    docker:
      memory: 7128
  caches:
    sonar: ~/.sonar
  steps:
    - step: &sonarqube
        name: SonarQube analysis
        image: maven:3.3.9
        script:
          - echo "sonar.projectKey=${SONAR_PROJECT_KEY}" > sonar-project.properties
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
              SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
        size: 2x 
        
    - step: &deploy_service
        name: Deploy Service on Server
        script:
          - *setenv
          - cd /home/ubuntu/aquacity/frontend
          - unset DOCKER_HOST
          - docker-compose down --rmi all | true
          - export WEB_PORTAL_TAG="${DOCKER_REPO}:${BITBUCKET_TAG}"
          - sed 's#__WEB_PORTAL_TAG__#'$WEB_PORTAL_TAG'#' docker-compose.yaml.template > docker-compose.yaml
          - docker-compose up -d

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build & Test
          image: node:lts
          caches:
            - node
          script:
            - yarn install --frozen-lockfile --cache-folder .yarn
            - yarn tsc
            - yarn lint

      - step:
          <<: *sonarqube
  tags:
    ####################################
    ############ CI For STG ############
    ####################################
    '*.*.*-stg':
      - step:
          name: STG - Build & Push Image
          script:
            - *setenv
            - export NEW_IMAGE_TAG=${DOCKER_REPO}:${BITBUCKET_TAG}
            - >-
              docker build . --file ${DOCKERFILE_PATH} --tag ${IMAGE_TAG}
              --build-arg REACT_APP_API_BASE_URL=https://aquacity.staging.novaid.vn/web/api
            - *retag_and_push_images
          services:
            - docker
          caches:
            - docker
          size: 2x

    ####################################
    ############ CI For UAT ############
    ####################################
    '*.*.*-uat':
      - step:
          name: UAT - Update image tag
          script:
            - *setenv
            - export NEW_IMAGE_TAG=${DOCKER_REPO}:${BITBUCKET_TAG}
            - >-
              docker build . --file ${DOCKERFILE_PATH} --tag ${IMAGE_TAG}
              --build-arg REACT_APP_API_BASE_URL=https://aquacity.uat.novaid.vn/web/api
            - *retag_and_push_images
          services:
            - docker
          caches:
            - docker
          size: 2x

    ####################################
    ######### CI For PREPRD,PRD ########
    ####################################
    '*.*.*':
      - step:
          name: PREPRD - Release Image On PREPRD
          script:
            - *setenv
            - export NEW_IMAGE_TAG=${DOCKER_REPO}:${BITBUCKET_TAG}-preprd
            - >-
              docker build . --file ${DOCKERFILE_PATH} --tag ${IMAGE_TAG}
              --build-arg REACT_APP_API_BASE_URL=https://aquacity.preprd.novaid.vn/web/api
            - *retag_and_push_images
          services:
            - docker
          caches:
            - docker
          size: 2x
          
      - step:
          name: PRD - Release Image On PRD
          script:
            - *setenv
            - export NEW_IMAGE_TAG=${DOCKER_REPO}:${BITBUCKET_TAG}-prd
            - >-
              docker build . --file ${DOCKERFILE_PATH} --tag ${IMAGE_TAG}
              --build-arg REACT_APP_API_BASE_URL=https://aquacity.novaid.vn/web/api
            - *retag_and_push_images
          services:
            - docker
          caches:
            - docker
          size: 2x
          trigger: manual
